### ISSUE TITLE
TypeError: clamp(): argument 'min' (position 2) must be Number, not Tensor

### ISSUE THREAD

**Issue by tuoli9** [dreamflake/ODI#1]
An interesting work. But there was a bug in attacks.py

```
File "./ODI/attacks.py", line 658, in advanced_fgsm
    x_adv = torch.clamp(x_adv, x_min, x_max)
TypeError: clamp(): argument 'min' (position 2) must be Number, not Tensor
```

**Comment by dreamflake** [comment]
Thank you for your interest in our work.

torch.clamp(input, min=None, max=None, *, out=None) supports Tensor data type for min/max argument from PyTorch v1.9.

Please see [the API reference](https://pytorch.org/docs/1.9.0/generated/torch.clamp.html?highlight=clamp#torch.clamp).

If you are using PyTorch v1.8 or earlier version, we recommend upgrading PyTorch.

Thank you.

**Comment by tuoli9** [comment]
You're right, thanks for your reply
